services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Environment variables based on .env.example
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/postgres
      - DEBUG=True
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aws-otel-collector:4317
    depends_on:
      db:
        condition: service_healthy
      aws-otel-collector:
        condition: service_started

  db:
    image: postgres:18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  aws-otel-collector:
    image: amazon/aws-otel-collector:latest
    command: ["--config=/etc/otel-local-config.yaml"]
    volumes:
      - ./otel-local-config.yaml:/etc/otel-local-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Jaeger UI

volumes:
  postgres_data:
